name: "Continuous integration checks"

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  # Allow manually triggering the workflow (in case something breaks).
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  syntax-errors:
    name: "Syntax errors checks"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "PHP setup"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"
          coverage: "none"
          tools: composer:v2

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          # Bust the cache at least once a month - output format: YYYY-MM.
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: "Validate Composer configuration"
        run: "composer validate --strict"

      - name: "Check for syntax errors"
        run: "composer test:lint"

  phpcs:
    name: "PHPCS check on PHP ${{ matrix.php }}"
    needs:
      - "syntax-errors"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        php: ["8.3", "8.4"]
    continue-on-error: "${{ matrix.php == '8.4' }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "PHP setup"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "none"
          tools: composer:v2, cs2pr

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: "Check coding standards using PHPCS"
        id: phpcs
        run: "composer test:standards -- --runtime-set --report-full --report-checkstyle=./phpcs-report.xml"

      - name: "Show PHPCS results in PR"
        if: "${{ always() && steps.phpcs.outcome == 'failure' }}"
        run: "cs2pr ./phpcs-report.xml"

  pest:
    name: "Unit tests on PHP ${{ matrix.php }}"
    needs:
      - "syntax-errors"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        php: ["8.3", "8.4"]
    continue-on-error: "${{ matrix.php == '8.4' }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "PHP setup"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "none"
          tools: composer:v2

      - name: "Install dependencies"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "highest"
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: "Run unit tests using Pest"
        id: pest
        run: "composer test:unit"
